# Generated by Django 4.0.1 on 2023-01-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, help_text='Enter address of customer or Company', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, help_text='Enter the city of the address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, help_text='Enter the country of the address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter the email of the customer or                               Company', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Enter Customer or Company', max_length=256),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(blank=True, help_text='Enter the region of the address', max_length=50, null=True),
        ),
    ]
